id: P007014
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:36:16.985200
source_metadata:
  id: bdr:W8231
  title: དབྱངས་ཅན་བྱཱ་ཀ་ར་ཎའི་མཚམས་སྦྱོར་ལྔ་པ
  author: ''
  volumes:
    14f52a6942874c3a8fb6ff99b56d8dcc:
      image_group_id: I1CZ982
      title: ''
      volume_number: 1
      total_pages: 170
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
