id: P007014
initial_creation_type: ocr
source_metadata:
  id: bdr:W8231
  title: དབྱངས་ཅན་བྱཱ་ཀ་ར་ཎའི་མཚམས་སྦྱོར་ལྔ་པ
  author: ''
  volumes:
    51573fabffbd4a22a10126b209cb59ad:
      image_group_id: I1CZ982
      title: Volume 5 of gsung 'bum/_gzhan phan chos kyi snang ba
      volume_number: 1
      total_pages: 170
      base_file: v001.txt
ebook_metadata:
  title: དབྱངས་ཅན་བྱཱ་ཀ་ར་ཎའི་མཚམས་སྦྱོར་ལྔ་པ
  author: ''
  sku: P007014
  cover: cover.jpg
  layers:
  - pagination
