id: ID7447348
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:54:22+00:00'
last_modified: '2022-06-08T12:00:38.319986+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8231
  title: དབྱངས་ཅན་བྱཱ་ཀ་ར་ཎའི་མཚམས་སྦྱོར་ལྔ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0216':
      image_group_id: I1CZ982
      title: ''
      total_pages: 170
      order: 1
      base_file: 0216.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
