id: ID7447348
legacy_id: P007014
ocr_import_info:
  bdrc_scan_id: W8231
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:53:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:18:49.529721+00:00'
last_modified: 2022-09-04 11:18:57.477812
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8231
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8231
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབྱངས་ཅན་བྱཱ་ཀ་ར་ཎའི་མཚམས་སྦྱོར་ལྔ་པ།
  author: སྡེ་སྲིད་སངས་རྒྱས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.49607122532652925
  ocr_word_median_confidence_index: 0.4300000071525574
quality: null
bases:
  I1CZ982:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ982
      total_pages: 170
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ982.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.49607122532652925
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
